version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/warehouseapp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_PORT: 8081
    depends_on:
      - db
    volumes:
      - maven-repo:/root/.m2

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: warehouseapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    command: [ "postgres", "-p", "5432" ]

volumes:
  db_data:
  maven-repo: